language: java

script: "mvn cobertura:cobertura"

dist: trusty
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - jdk: oraclejdk7
    - jdk: openjdk7
    - jdk: oraclejdk8
    - jdk: openjdk8
    - jdk: oraclejdk9
    - jdk: openjdk9
    - jdk: oraclejdk10
    - jdk: openjdk10
