name: Java CI

on:   
  push:
    branches:
    - master
    - dev
  schedule:
  - cron: "0 12 1 * *"
  pull_request:
    branches:
    - master
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
    name: Java ${{ matrix.java }} setup

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Gradle
      run: ./gradlew build
